# Generated by Django 5.1.7 on 2025-03-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='content',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
